### ISSUE TITLE
DecodeAddressString and EncodeAddressBytes broken

### ISSUE THREAD

**Issue by nwatson22** [runtimeverification/avm-semantics#108]
These functions are found in [`teal-types.md`](https://github.com/runtimeverification/avm-semantics/blob/d9b65bef2a8575bffc921337d13d09c65d229ff5/lib/include/kframework/avm/teal/teal-types.md?plain=1#L179). They are only currently being used to [determine the byte encoding of the `ZeroAddress` field from the string](https://github.com/runtimeverification/avm-semantics/blob/d9b65bef2a8575bffc921337d13d09c65d229ff5/lib/include/kframework/avm/blockchain.md?plain=1#L31). They are `CLARITY` hooks, and I'm not sure how that works. I will link a PR that adds a test that demonstrates the issue. The test fails because when `getGlobalField(ZeroAddress)` is called, `IsAddressValid("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ" )` is not defined.

**Comment by malturki** [comment]
`IsAddressValid` is hooked to the cpp function `hook_CLARITY_check_address` in `hooks/hooks.cpp`, which checks whether a given string represents a valid Algorand address. I think this function will be useful beyond just checking the zero address (e.g. you can use it to check that an address string as given in an input TEAL program is a valid address -- I believe the reference TEAL interpreter makes this check for addresses). There are two more functions there in that file for encoding and decoding addresses that could also be potentially useful.

I think the reason why it gets stuck now is that the generated interpreter is not properly linked to the compiled hooks. Two things to check in `Makefile`:

1. The hooks are compiled before the semantics is built.
2. When compiling the semantics, `kompile` is pointed to where these libraries are and supplied with the appropriate kompile hook options, including the needed namespace specification.

It seems most of this is already there, but I haven't checked carefully. For example, the kompile hook options variable `AVM_HOOK_KOMPILE_OPTS` is already defined in `Makefile` but not used. So maybe just adding these options to the command invoking kompile to build the semantics would do. I'm not entirely sure, but ensuring (1) and (2) above should help resolve this issue. Let me know if you need further help with this.

**Comment by geo2a** [comment]
Thank you @malturki for the explanation! We need to figure out if we want to use hooks and how. I'll look into that.

**Comment by geo2a** [comment]
@malturki I've made sure the hooks are provided to `kompile`, but the problem still persists...

How do I make sure that the hooks are compiled before the semantics is built? Could you point me to the relevant bit in the `algorand-sc-semantics` repo's Makefile?
