### ISSUE TITLE
Run integration tests in CI

### ISSUE THREAD

**Issue by geo2a** [runtimeverification/avm-semantics#113]
# We don't run integration test in CI as intended

KAVM has an integration test suite that is implemented with `pytest` and `py-algorand-sdk`. The same test files could be run with two backends: KAVM and the Algorand Sandbox. However, we only run the tests with the KAVM backend on CI.

# Algorand Sandbox is running in Docker

The Algorand Sandbox is set in a Docker container with `docker-compose`, see [kavm/docker-compose.yaml](https://github.com/runtimeverification/avm-semantics/blob/master/kavm/docker-compose.yml).The problem is that the CI setup runs the project is a Docker container too, and we will have the Docker-in-Docker problem.

# Ways to proceed

I see two ways forward:
* include the Algorand Sandbox into the parent Docker image. The docker-compose setup can still be used for running the tests locally.
  - Pro: the top-level CI invocation infrastructure does not change
  - Contra: we use a customized Algorand Sandbox image prepared by [makerx](https://github.com/MakerXStudio/algorand-sandbox-dev). I do not think it will require a lot of effort to replicate it, but it's still work.
* Refactor the top-level setup to use docker-compose and keep the two images: the KAVM one and the Algorand Sandbox one.
  - Pro: can reuse the existing Algorand Sandbox setup.
  - Contra: need to use docker-compose in Jenkins. Probably it's easy?

I'd like peoples input on what's best. To me both options seem fine.

**Comment by ehildenb** [comment]
Make sure to sync with @F-WRunTime on your CI setup to make sure you are:

- Not leaving containers around (make sure `docker stop` is called)
- Making best use of our docker caching.

**Comment by geo2a** [comment]
Points of reference:

* Template dockerized build workflow: https://github.com/runtimeverification/devops-actions/blob/master/.github/workflows/BuildDockerInTemplate.yaml
* KSummarizer testing workflow: https://github.com/runtimeverification/ksummarize/blob/master/.github/workflows/test.yml
