### ISSUE TITLE
Install KAVM with `kup`

### ISSUE THREAD

**Issue by geo2a** [runtimeverification/avm-semantics#147]
To streamline the installation of KAVM for potential users', we need to integrate KAVM with the `kup` tool.

**Comment by geo2a** [comment]
KAVM will be supported by `kup`, see [this issue](https://github.com/runtimeverification/kup/issues/7) in the `kup`'s repo.

**Comment by goodlyrottenapple** [comment]
fixed by https://github.com/runtimeverification/kup/pull/9
