### ISSUE TITLE
Investigate performance of `#initTxnIndexMap()`

### ISSUE THREAD

**Issue by geo2a** [runtimeverification/avm-semantics#287]
The [`#initTxnIndexMap()`](https://github.com/runtimeverification/avm-semantics/blob/eb136a5604b8228b09f4f1443792d141d0e83578/lib/include/kframework/avm/avm-initialization.md?plain=1#L75) rule traverses the `<transaction>` cell and builds the `<txnIndexMap>`, a service cell which clusters the transactions by their groups and maintains a reverse index from group indices to transaction ids.

The `#initTxnIndexMap()` rule will be executed when a transaction group evaluation is triggered by the `#evalTxGroup()` rule, which fires both when the initial (outer) group is evaluated and an inner group is evaluated.

We suspect that this rule is expensive to execute, and we would like to determine how, in fact, expensive it is.

As an initial step, we should investigate the [tests/specs/calls/buy-asset-spec.md](https://github.com/runtimeverification/avm-semantics/blob/master/tests/specs/calls/buy-asset-spec.md):
* create a variant of this spec that has the `<txnIndexMap>` cell pre-built.
* compare execution time with the base spec
* ideally, figure out a way to do rule-level profiling

**Comment by nwatson22** [comment]
I tried the test you suggested in the linked branch. There seems to be about a 10 second speedup between the two (160 vs. 170 seconds). I'm guessing this means that these are a bit slower than the average rewrite, but not that much worse. Was there an example where it seemed to be causing problems?

**Comment by geo2a** [comment]
Thanks @nwatson22. OK, I'll be closing it for now.
