### ISSUE TITLE
Improved test harness

### ISSUE THREAD

**Issue by nwatson22** [runtimeverification/avm-semantics#59]
Right now for concrete tests we only verify that `tests/scenarios/*.avm-simulation` tests finish execution and that `tests/scenarios/*.fail.avm-simulation` tests do not. For more granular testing we should change the Makefile so the final configuration is compared to an expected output, similar to how some tests are executed in the [KEVM repo](https://github.com/runtimeverification/evm-semantics/blob/master/Makefile). I was not sure on exactly how to split up the different categories of tests, though. Would it be better to have this as an optional type of test or apply it to all concrete execution tests, or only apply it to failure tests?

Originally suggested at: https://github.com/runtimeverification/avm-semantics/pull/57#discussion_r935091467

**Comment by geo2a** [comment]
This issue has been addressed by running scenarios with the Python `kavm` runner and checking the result.
